### ISSUE TITLE
Final_Project

### ISSUE THREAD

**Issue by Hongbin-Chen** [QMSS-G5072-2020/Final_Project_ChenHongbin#1]
b481790

@SUN-Wenjun 
@lonadai0121
@tbrambor

**Comment by lonadai0121** [comment]
2/5 below average project: only some development of functionality with limited skills performed
3/3 well commented and documented
2/3 The code is efficient, correct, and minimal, but again, too straightforward.
3/3 The package structure is clear, easy to follow, and closely matches the structure discussed in class.
3/3 The package, data, and functions’ documentation is clear and easy to follow.
3/3 The package installs without problems.
2/3 Only one test case.
